### ISSUE TITLE
ConsentInformation.update callbacks are called repeatedly

### ISSUE THREAD

**Issue by abcjjy** [poingstudios/godot-admob-plugin#134]
### Godot version

4.2

### Plugin version

3.1.0

### System information

Godot v4.2.stable - macOS 13.6.1 - GLES3 (Compatibility) - ANGLE (AMD, ANGLE Metal Renderer: AMD Radeon Pro 560X, 版本13.6.1（版号22G313）) - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 Threads)

### Phone information, if applicable

iPhone X iOS 14.8

### Issue description

Each time ConsentInformation.update is called, new callbacks are connected to the inner signals. In later call to update(), previous callbacks are also fired.

An option is passing Callables into native plugin instead of using signals.

UserMessagingPlatform.load_consent_form has similar issues too.

### Steps to reproduce

Call ConsentInformation.update multiple times, all the used callbacks are called.

**Comment by gumaciel** [comment]
thank you for opening this issue, i will verify this

**Comment by gumaciel** [comment]
@abcjjy fixed at https://github.com/poingstudios/godot-admob-plugin/releases/tag/v3.1.1, please test it
