### ISSUE TITLE
Unable to download the plugin

### ISSUE THREAD

**Issue by zorro0799** [poingstudios/godot-admob-plugin#144]
### Godot version

4.2.2

### Plugin version

3.0.3

### System information

Monterrey 12.7.5

### Issue description

Unable to download the plugin, always reports ERR_002 error. According to the ERR_002.md document, the network test is fine. https://github.com/poingstudios/godot-admob-android/releases/download/v3.0.3/poing-godot-admob-android-v4.2.2.zip cannot be downloaded, but https://github.com/poingstudios/godot-admob-android/releases/download/v3.0.3/poing-godot-admob-android-v4.2.2.zip can be downloaded. I changed the gd file to the download URL of 3.0.3, but it still cannot be downloaded. How can I solve this problem?

### Steps to reproduce

1. var version_support := {
	"android": "v3.0.3",
	"ios": "v3.0.3"
}
2. In the function _on_android_popupmenu_id_pressed, replace the Poing-Studios string with poingstudios, and spell out the new download address https://github.com/poingstudios/godot-admob-android/releases/download/v3.0.3/poing-godot-admob-android-v4.2.2.zip
3. try manually downloading it from the `Project->Tools->Android Download Manager->Android/iOS->LatestVersion` section.

**Comment by zorro0799** [comment]
The result is
Downloading https://github.com/poingstudios/godot-admob-android/releases/download/v3.0.3/poing-godot-admob-android-v4.2.2.zip
Download percent: 0%
ERR_002: It is not possible to download the Android/iOS plugin.
Read more about on: res://addons/admob/docs/errors/ERR_002.md

**Comment by zorro0799** [comment]
I'm sure the network is good, and manually downloading https://github.com/poingstudios/godot-admob-android/releases/download/v3.0.3/poing-godot-admob-android-v4.2.2.zip is successful. I've tried using godot with and without a proxy, and neither works.

**Comment by gumaciel** [comment]
Hi, it's working now?

**Comment by gumaciel** [comment]
Closing this issue due lack of response.

I tested here and it's download normally on https://github.com/poingstudios/godot-admob-android/releases/download/v3.0.3/poing-godot-admob-android-v4.2.2.zip, try to use some VPN to check if still persists 

If still persists please re-open.
