### ISSUE TITLE
4.2.2 does not work

### ISSUE THREAD

**Issue by powerlsj7** [poingstudios/godot-admob-plugin#145]
### Godot version

4.2.2

### Plugin version

3.1.1

### System information

windows 11

### Issue description

안녕하세요? 4.2.2 고도엔진으로 admob 플러그인을 다운받아 사용했고, 중간에 plugins폴더도 만들어 lib파일도 압축을 풀고 넣어두었습니다. 하지만 샘플씬을 에디터에서 실행하고 로드버튼을 눌러도 아무런 반응이 없습니다. 빌드 후 모바일 화면으로 터치해도 똑같습니다. 아직 4.2.2에서는 사용할 수 없는건가요? 

translate:

hello? 4.2.2 I downloaded and used the admob plugin with Godot Engine, created a plugins folder in the middle, unzipped the lib file, and placed it there. However, when I run the sample scene in the editor and press the load button, there is no response. Even if you touch it with the mobile screen after building it, it is the same. Is it not available in 4.2.2 yet?

https://poingstudios.github.io/godot-admob-plugin/

### Steps to reproduce

![323](https://github.com/user-attachments/assets/82ee0170-1e39-4883-a8a4-b044487be755)

### Additional context

![323](https://github.com/user-attachments/assets/821945fa-448e-4676-91b9-c76bb4a093f4)

**Comment by gumaciel** [comment]
If you are testing on PC, it won't work, just on mobile devices

Closing this issue since seems you are testing on PC
