### ISSUE TITLE
android same doesn't work[resolve]

### ISSUE THREAD

**Issue by powerlsj7** [poingstudios/godot-admob-plugin#146]
### Godot version

4.2.2

### Plugin version

3.1.1

### System information

windows 11

### Phone information, if applicable

android api level 6 xaomi redmi note4

### Issue description

android same
doesn't work

### Steps to reproduce

![KakaoTalk_20240825_201804179_01](https://github.com/user-attachments/assets/d59d01a6-af3f-42ac-ba0b-ffcb78d9a53c)
![KakaoTalk_20240825_201804179](https://github.com/user-attachments/assets/b57e9018-e5fc-44c3-abc1-bd6e19d28543)

**Comment by powerlsj7** [comment]
extends Node


var interstitial_ad : InterstitialAd
var interstitial_ad_load_callback := InterstitialAdLoadCallback.new()
@onready var label = $Label
func _ready():
	MobileAds.initialize()
	interstitial_ad_load_callback.on_ad_failed_to_load = on_interstitial_ad_failed_to_load
	interstitial_ad_load_callback.on_ad_loaded = on_interstitial_ad_loaded
		
# button signal on scene
func _on_load_interstitial_pressed() -> void:
	#free memory
	if interstitial_ad:
		#always call this method on all AdFormats to free memory on Android/iOS
		interstitial_ad.destroy()
		interstitial_ad = null
	var unit_id : String
	if OS.get_name() == "Android":
		unit_id = "ca-app-pub-3940256099942544/1033173712"
	elif OS.get_name() == "iOS":
		unit_id = "ca-app-pub-3940256099942544/4411468910"
	label.text="광고준비 눌림"
	InterstitialAdLoader.new().load(unit_id, AdRequest.new(), interstitial_ad_load_callback)
	
func on_interstitial_ad_failed_to_load(adError : LoadAdError) -> void:
	print(adError.message)

func on_interstitial_ad_loaded(interstitial_ad : InterstitialAd) -> void:
	self.interstitial_ad = interstitial_ad
# button signal on scene
func _on_show_pressed():
	label.text="보여주는 버튼 클릭"
	if interstitial_ad:
		label.text="광고온"
		interstitial_ad.show()	


func _on_button_2_pressed():
	_on_show_pressed()



func _on_button_pressed():
	_on_load_interstitial_pressed()

**Comment by powerlsj7** [comment]
![image](https://github.com/user-attachments/assets/db2239a9-7c4b-4715-8459-99067fd2a602)
This is my editor situation and the test node is using the script I left above.

**Comment by powerlsj7** [comment]
![image](https://github.com/user-attachments/assets/13b402b9-c56d-470e-8a73-ddf1534c8c7d)

**Comment by powerlsj7** [comment]
![image](https://github.com/user-attachments/assets/ef9b07c0-514e-4860-99ba-c6670c05ae7f)
I found the official documentation and followed it exactly: I downloaded the latest admob libs to GodoEditor and moved the libs file from the ads file.
Is this working correctly in 4.2.2? Or does it not work because my android version is not up to the minimum, in which case I have to make my own?

**Comment by powerlsj7** [comment]
![image](https://github.com/user-attachments/assets/8a780901-6e50-421d-ade2-0df280ca47ea)
What it looks like after installation 
Press the play button and the ad should appear if it is ready. But it looks like it's not ready.
![image](https://github.com/user-attachments/assets/eae09355-8ef3-4805-a82a-d66ac717d87d)
![image](https://github.com/user-attachments/assets/3da186f7-69a6-4a4c-ac2d-7245fa0a17db)

**Comment by powerlsj7** [comment]
![image](https://github.com/user-attachments/assets/bdb0c102-71f5-499c-aada-8c6efbeee50a)
When I change the value of a file in the Kodo project, even if I turn off Kodo Engine and restart it, the program keeps running somewhere and I can't delete or move the file, so I have to reset the Windows operating system and work on it. Please fix this bug!
![image](https://github.com/user-attachments/assets/d6b57b77-4a75-4d22-a96b-114820271556)

**Comment by powerlsj7** [comment]
I went a little further and ran elevation engine in admin mode and saw the export plugin item that I didn't see, checked it and exported but realized that the SDK doesn't support Android 22. I tried to fix it myself but it's already compiled with AAR and I can't do anything about it.
Why should I abandon the installation for users with android 22-23. Do you have any plans to support 22-23 or do I have to make it myself?
![image](https://github.com/user-attachments/assets/4a32e2a3-a82e-4309-9ed8-deb52bf09ffa)

**Comment by gumaciel** [comment]
@powerlsj7 is your issue persisting? 

I've tested it here and it's working great

If not, please join on Discord: https://discord.com/invite/YEPvYjSSMk and we can help you quickly 

Closing this issue because seems to be a configuration problem.
